/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swerve;

import static org.junit.Assert.*;

import org.junit.Test;

public class Vector2Test {

  @Test
  public void dotProduct() {
    assertEquals(new Vector2(1, 2).dot(new Vector2(5, -3)), -1, 0.001);
    assertEquals(new Vector2(5, -3).dot(new Vector2(1, 2)), -1, 0.001);
  }
}
